export const Posts = [
  {
    id: 1,
    author: "Arnav Anand",
    date: "7th Oct | 14:00",
    status: "OPEN",
    description:
      "Our area has been severely flooded, and many of us are stranded. We urgently need clean drinking water, food supplies, and medical assistance.",
    image:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    category: "Flood, Medical, Infrastructure",
    severity: "High",
    urgency: "High",
    distance: "3.5 Km",
    location: "Khadakwasla",
  },
  {
    id: 2,
    author: "John Doe",
    date: "8th Oct | 15:30",
    status: "CLOSED",
    description:
      "We are looking for volunteers to assist with shelter for displaced families after the recent earthquake.",
    image:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    category: "Shelter, Medical",
    severity: "Medium",
    urgency: "Medium",
    distance: "1.2 Km",
    location: "Downtown",
  },
  {
    id: 3,
    author: "Jane Smith",
    date: "9th Oct | 10:00",
    status: "OPEN",
    description:
      "Urgent need for food and blankets in the affected area after the landslide.",
    image:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    category: "Food, Shelter",
    severity: "High",
    urgency: "High",
    distance: "5.0 Km",
    location: "Highland",
  },
  {
    id: 4,
    author: "Mike Johnson",
    date: "10th Oct | 12:30",
    status: "OPEN",
    description:
      "Medical assistance required for injured individuals following the fire outbreak.",
    image:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    category: "Medical, Fire",
    severity: "Critical",
    urgency: "Immediate",
    distance: "2.8 Km",
    location: "City Center",
  },
  {
    id: 5,
    author: "Emily Brown",
    date: "11th Oct | 09:15",
    status: "CLOSED",
    description:
      "Community needs support in rebuilding homes damaged by the storm.",
    image:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    category: "Reconstruction, Shelter",
    severity: "Medium",
    urgency: "Low",
    distance: "4.5 Km",
    location: "West Side",
  },
  {
    id: 6,
    author: "Rachel Green",
    date: "12th Oct | 11:45",
    status: "OPEN",
    description:
      "Collecting donations for victims of the recent earthquake. Every bit helps!",
    image:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    category: "Donations, Food",
    severity: "Medium",
    urgency: "High",
    distance: "1.0 Km",
    location: "East Valley",
  },
  {
    id: 7,
    author: "Chris Evans",
    date: "13th Oct | 08:30",
    status: "OPEN",
    description:
      "Seeking volunteers to distribute food and water in the flood-hit areas.",
    image:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    category: "Food, Volunteers",
    severity: "High",
    urgency: "Immediate",
    distance: "6.3 Km",
    location: "Riverbank",
  },
  {
    id: 8,
    author: "Sophia Turner",
    date: "14th Oct | 16:00",
    status: "OPEN",
    description:
      "Need urgent medical supplies for a health camp in the disaster zone.",
    image:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    category: "Medical, Supplies",
    severity: "Critical",
    urgency: "High",
    distance: "2.0 Km",
    location: "North Hill",
  },
  {
    id: 9,
    author: "David Williams",
    date: "15th Oct | 13:00",
    status: "CLOSED",
    description:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    image: "https://example.com/image9.jpg",
    category: "Reconstruction",
    severity: "Low",
    urgency: "Low",
    distance: "4.0 Km",
    location: "Old Town",
  },
  {
    id: 10,
    author: "Olivia Martinez",
    date: "16th Oct | 14:30",
    status: "OPEN",
    description:
      "Looking for support in providing clean water to families affected by the drought.",
    image:
      "https://image.cnbcfm.com/api/v1/image/107077924-1655579857423-gettyimages-1241322120-INDIA-ASSAM-GUWAHATI-FLOOD.jpeg?v=1655580320&w=1480&h=833&ffmt=webp&vtcrop=y",
    category: "Water, Supplies",
    severity: "High",
    urgency: "High",
    distance: "3.0 Km",
    location: "Sunnydale",
  },
];

export const Categories = [
  "Food",
  "Medical Supplies",
  "Shelter",
  "Clothing",
  "Clean Water",
  "Sanitation Supplies",
  "Communication Devices",
  "Other",
  "First Aid Kits",
  "Cooking Equipment",
  "Hygiene Products",
  "Blankets",
  "Flashlights",
  "Batteries",
  "Tents",
  "Child Care Supplies",
  "Pet Care Supplies",
  "Fuel",
  "Transportation Assistance",
  "Psychological Support Resources",
];
export const Keywords = [
  "urgent medical needs",
  "food donations",
  "shelter request",
  "clothing for children",
  "transport to hospital",
  "psychological counseling",
  "medical supplies needed",
  "temporary housing assistance",
  "clean drinking water",
  "first aid kits",
  "baby supplies needed",
  "warm clothing",
  "emergency shelter",
  "fuel assistance",
  "volunteer support",
  "financial aid request",
  "housing relocation help",
  "counseling for trauma",
];
export const Steps = [
  "Describe Your Problem",
  "Select the Location",
  "Preview and Publish",
];
